CREATE TABLE [dbo].[Document] (
    [Id]   UNIQUEIDENTIFIER CONSTRAINT [DEFAULT_Document_Id] DEFAULT (newid()) NOT NULL PRIMARY KEY CLUSTERED ([Id] ASC),
    [Name] NVARCHAR (255)   NOT NULL,
    [Path] NVARCHAR (255)   NOT NULL
);
