CREATE TABLE [dbo].[Draft] (
    [Id]        UNIQUEIDENTIFIER CONSTRAINT [DEFAULT_Draft_Id] DEFAULT (newid()) NOT NULL PRIMARY KEY CLUSTERED ([Id] ASC),
    [CompanyId] UNIQUEIDENTIFIER NOT NULL,
    [Name]      NVARCHAR (255)   NOT NULL
);
