// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import mssql "github.com/microsoft/go-mssqldb"

const TableNameDocument = "Document"

// Document mapped from table <Document>
type Document struct {
	ID           mssql.UniqueIdentifier `gorm:"column:Id;primaryKey;default:newid()" json:"Id"`
	Name         string                 `gorm:"column:Name;not null" json:"Name"`
	Path         string                 `gorm:"column:Path;not null" json:"Path"`
	DraftHistory []DraftHistory         `gorm:"foreignKey:FileID" json:"draft_history"`
}

// TableName Document's table name
func (*Document) TableName() string {
	return TableNameDocument
}
