// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import mssql "github.com/microsoft/go-mssqldb"

const TableNameDraft = "Draft"

// Draft mapped from table <Draft>
type Draft struct {
	ID           mssql.UniqueIdentifier `gorm:"column:Id;primaryKey;default:newid()" json:"Id"`
	CompanyID    mssql.UniqueIdentifier `gorm:"column:CompanyId;not null" json:"CompanyId"`
	Name         string                 `gorm:"column:Name;not null" json:"Name"`
	DraftHistory []DraftHistory         `gorm:"foreignKey:DraftID" json:"draft_history"`
}

// TableName Draft's table name
func (*Draft) TableName() string {
	return TableNameDraft
}
