// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	mssql "github.com/microsoft/go-mssqldb"
)

const TableNameDraftHistory = "DraftHistory"

// DraftHistory mapped from table <DraftHistory>
type DraftHistory struct {
	ID       mssql.UniqueIdentifier `gorm:"column:Id;primaryKey;default:newid()" json:"Id"`
	DraftID  mssql.UniqueIdentifier `gorm:"column:DraftId;not null" json:"DraftId"`
	FileID   mssql.UniqueIdentifier `gorm:"column:FileId;not null" json:"FileId"`
	UserID   mssql.UniqueIdentifier `gorm:"column:UserId;not null" json:"UserId"`
	Date     time.Time              `gorm:"column:Date;not null" json:"Date"`
	Title    string                 `gorm:"column:Title;not null" json:"Title"`
	Message  string                 `gorm:"column:Message" json:"Message"`
	Draft    Draft                  `gorm:"foreignKey:DraftID;references:ID" json:"draft"`
	Document Document               `gorm:"foreignKey:FileID;references:ID" json:"document"`
}

// TableName DraftHistory's table name
func (*DraftHistory) TableName() string {
	return TableNameDraftHistory
}
