// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import mssql "github.com/microsoft/go-mssqldb"

const TableNameCompany = "Company"

// Company mapped from table <Company>
type Company struct {
	ID          mssql.UniqueIdentifier `gorm:"column:Id;primaryKey;default:newid()" json:"Id"`
	Name        string                 `gorm:"column:Name;not null" json:"Name"`
	Permissions []Permission           `gorm:"foreignKey:RoleID" json:"permissions"`
	Users       []User                 `gorm:"-:all" json:"users"`
}

// TableName Company's table name
func (*Company) TableName() string {
	return TableNameCompany
}
