// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import mssql "github.com/microsoft/go-mssqldb"

const TableNamePermission = "Permission"

// Permission mapped from table <Permission>
type Permission struct {
	ID        mssql.UniqueIdentifier `gorm:"column:Id;primaryKey;default:newid()" json:"Id"`
	UserID    mssql.UniqueIdentifier `gorm:"column:UserId;not null" json:"UserId"`
	RoleID    mssql.UniqueIdentifier `gorm:"column:RoleId;not null" json:"RoleId"`
	CompanyID mssql.UniqueIdentifier `gorm:"column:CompanyId" json:"CompanyId"`
	User      User                   `gorm:"foreignKey:UserID;references:ID" json:"user"`
	Role      Role                   `gorm:"foreignKey:RoleID;references:ID" json:"role"`
	Company   Company                `gorm:"foreignKey:CompanyID;references:ID" json:"company"`
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
