// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import mssql "github.com/microsoft/go-mssqldb"

const TableNameRole = "Role"

// Role mapped from table <Role>
type Role struct {
	ID        mssql.UniqueIdentifier `gorm:"column:Id;primaryKey;default:newid()" json:"Id"`
	Name      string                 `gorm:"column:Name;not null" json:"Name"`
	UserRoles []UserRole             `gorm:"foreignKey:RoleID" json:"user_roles"`
	Users     []User                 `gorm:"-:all" json:"users"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
