// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import mssql "github.com/microsoft/go-mssqldb"

const TableNameUser = "User"

// User mapped from table <User>
type User struct {
	ID           mssql.UniqueIdentifier `gorm:"column:Id;primaryKey;default:newid()" json:"Id"`
	Email        string                 `gorm:"column:Email;not null" json:"Email"`
	Username     string                 `gorm:"column:Username;not null" json:"Username"`
	PasswordHash string                 `gorm:"column:PasswordHash;not null" json:"PasswordHash"`
	Salt         string                 `gorm:"column:Salt;not null" json:"Salt"`
	RefreshToken string                 `gorm:"column:RefreshToken" json:"RefreshToken"`
	UserRoles    []UserRole             `gorm:"foreignKey:UserID" json:"user_roles"`
	Roles        []Role                 `gorm:"-:all" json:"roles"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
