// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import mssql "github.com/microsoft/go-mssqldb"

const TableNameUserRole = "UserRole"

// UserRole mapped from table <UserRole>
type UserRole struct {
	ID     mssql.UniqueIdentifier `gorm:"column:Id;primaryKey;default:newid()" json:"Id"`
	UserID mssql.UniqueIdentifier `gorm:"column:UserId;not null" json:"UserId"`
	RoleID mssql.UniqueIdentifier `gorm:"column:RoleId;not null" json:"RoleId"`
	User   User                   `gorm:"foreignKey:UserID;references:ID" json:"user"`
	Role   Role                   `gorm:"foreignKey:RoleID;references:ID" json:"role"`
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
