// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import mssql "github.com/microsoft/go-mssqldb"

const TableNameUser = "User"

// User mapped from table <User>
type User struct {
	ID             mssql.UniqueIdentifier `gorm:"column:Id;primaryKey;default:newid()" json:"Id"`
	Email          string                 `gorm:"column:Email;not null" json:"Email"`
	Username       string                 `gorm:"column:Username" json:"Username"`
	PasswordHash   string                 `gorm:"column:PasswordHash" json:"PasswordHash"`
	Salt           string                 `gorm:"column:Salt" json:"Salt"`
	RefreshToken   string                 `gorm:"column:RefreshToken" json:"RefreshToken"`
	Firstname      string                 `gorm:"column:Firstname" json:"Firstname"`
	Lastname       string                 `gorm:"column:Lastname" json:"Lastname"`
	Code           string                 `gorm:"column:Code" json:"Code"`
	PasswordChange bool                   `gorm:"column:PasswordChange" json:"PasswordChange"`
	Permissions    []Permission           `gorm:"foreignKey:UserID" json:"permissions"`
	Roles          []Role                 `gorm:"-:all" json:"roles"`
	Company        Company                `gorm:"-:all" json:"company"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
